name: Setup env
description: Sets up node and pnpm
inputs:
  pnpm-version:
    description: Version of pnpm to install
    required: false
    default: 9 node-version
    description: Version of node to install
    required: false
    default: "18"
  cache-save:
    description: Whether to save the pnpm cache
    required: false
    default: false
outputs:
  cache-hit:
    description: Whether the cache was restored
    value: ${{ steps.setup-node.outputs.cache-hit || steps.cache-restore.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@v4
      id: setup-node
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache-save == 'true' && 'pnpm' || '' }}
        cache-dependency-path: "/pnpm-lock.yaml"
        key: node-cache-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
